### ISSUE TITLE
OSX Compiled binary and Brew Formulas

### ISSUE THREAD

**Issue by rmb938** [owainlewis/relay#1]
It would be nice to have a binary compiled for osx and brew formulas so relay can be installed via homebrew.

**Comment by owainlewis** [comment]
Will get on it ASAP thanks :+1:

**Comment by marcosArruda** [comment]
+1

**Comment by owainlewis** [comment]
Added OSX binaries https://github.com/owainlewis/relay/releases. Homebrew will be a separate task. Thanks.
